### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by galenyuan** [galenyuan/vue-datepicker#1]
- [x] Optimizion
- [x] Rebuild with ES6
- [x] Basic picker function
- [ ] UI
- [ ] Panels
- [ ] Component in Javascript version
